name: "sizeof.io"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
extra:
   author: "Nico Hämäläinen"
   email: "nico@sizeof.io"
