# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            sizeof.io
tagline:          'Polybloat™ programmer, designer and thinker.'
description:      'Crazytalk about programming, design and inbetween. Written by <a href="https://twitter.com/clooth" target="_blank">@clooth</a>.'
url:              http://sizeof.io

author:
  name:           'Nico Hämäläinen'
  url:            https://twitter.com/clooth

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde